before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      386: 32-bit
      amd64: 64-bit
#    files:
#      - share/man/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  - name: tailspin
    tap:
      owner: bensadeh
      name: homebrew-tailspin
    description: "A better way to browse your logfiles"
    homepage: "https://github.com/bensadeh/tailspin/"
    license: "MIT"
    dependencies:
      - name: less
    install: |
      bin.install "tailspin" => "spin"
#      man1.install "#{buildpath}/share/man/clx.1"
