[package]
name = "tailspin"
version = "0.1.0"
edition = "2021"
authors = ["Ben Sadeh"]
description = "tailspin is a log file highlighter and a drop-in replacement for tail -f"
repository = "https://github.com/bensadeh/tailspin"
keywords = ["log", "syntax-highlighting", "tail", "less"]
license = "MIT"

[[bin]]
path = "src/main.rs"
name = "spin"

[dependencies]
tempfile = "3.2.0"
linemux = "0.3"
tokio = { version = "1", features = ["full"] }
